version: '3'

env:
  CONSOLE_ADDR: 192.168.0.161:5000 # can be overriden in .env
dotenv: [".env"]

tasks:
  research:
    desc: Reproduce research
    dir: research
    cmds:
    - python main.py {{.CLI_ARGS}}

  upload-console:
    aliases: [uc]
    dir: dump/console
    desc: Upload dumper mod to the console
    cmds:
    - lftp $CONSOLE_ADDR < scripts/lftp-upload.sh


#
# tasks:
#   build:
#     aliases: [b]
#     desc: Build the mod
#     cmds:
#       - megaton
#
#
#   download:
#     desc: Download logs and data from console
#     cmds:
#     - mkdir -p target/crash_reports/dumps
#     - lftp $CONSOLE_ADDR < scripts/lftp-download.sh
