version: '3'

env:
  CONSOLE_ADDR: 192.168.0.161:5000 # can be overriden in .env
dotenv: [".env"]

tasks:
  research:
    desc: Reproduce research
    dir: research
    cmds:
    - python main.py {{.CLI_ARGS}}

  upload:
    dir: dump/console
    desc: Upload dumper mod to the console
    cmds:
    - lftp $CONSOLE_ADDR < scripts/lftp-upload.sh

  configure:
    dir: dump/console
    desc: "Configure the console dump. Args: START END"
    cmds:
    - python scripts/config.py {{.CLI_ARGS}}
    - lftp $CONSOLE_ADDR < scripts/lftp-config.sh

  megaton:
    dir: dump/console
    cmds:
    - megaton

  download:
    dir: dump/console
    desc: Download dumps from console and rename them
    cmds:
    - mkdir -p raw
    - lftp $CONSOLE_ADDR < scripts/lftp-download.sh
    - task: rename

  rename:
    dir: dump/console
    desc: Rename dumps form console
    cmds:
    - python scripts/rename.py

  package:
    dir: dump/console
    desc: Package the mod
    vars:
      MOD_DIR: "target/package/mods/The Legend of Zelda - Breath of the Wild/Recipe Dumper/contents/01007EF00011E000"
    cmds:
      - megaton
      - rm -rf target/package/mods
      - mkdir -p "{{.MOD_DIR}}/exefs"
      - mkdir -p "{{.MOD_DIR}}/romfs"
      - cp target/megaton/none/main.npdm "{{.MOD_DIR}}/exefs/main.npdm"
      - cp target/megaton/none/botwrdump.nso "{{.MOD_DIR}}/exefs/subsdk9"
      - mkdir -p target/package/botwrdump
      - echo "" > target/package/botwrdump/.keep
      - cd target/package && zip -r ../botwrdump.zip .

  dump:
    dir: dump/emulate
    desc: Dump using cooking.rs
    cmds:
    - cargo run --release --bin rdump --quiet -- {{.CLI_ARGS}}

  check:
    dir: dump/tools
    aliases: [c]
    desc: Check dumps
    cmds:
    - cargo run --release --bin check --quiet -- {{.CLI_ARGS}}
    
  cook:
    dir: app/cook
    desc: Cook a recipe with emulator. Separate ingredients with commas
    cmds:
    - cargo run --bin rcook --quiet -- {{.CLI_ARGS}}

  cook-debug:
    dir: app/cook
    desc: Cook a recipe in debug mode
    cmds:
    - cargo run --bin rcook --features debug-print --features rng-hp {{.CLI_ARGS}}



#
# tasks:
#   build:
#     aliases: [b]
#     desc: Build the mod
#     cmds:
#       - megaton
#
#
#   download:
#     desc: Download logs and data from console
#     cmds:
#     - mkdir -p target/crash_reports/dumps
#     - lftp $CONSOLE_ADDR < scripts/lftp-download.sh
