version: '3'

env:
  CONSOLE_ADDR: 192.168.0.161:5000 # can be overriden in .env
dotenv: [".env"]

includes:
  rdb:
    taskfile: ./app/rdb
    dir: ./app/rdb

  console:
    taskfile: ./dump/console
    dir: ./dump/console

tasks:
  research:
    desc: Reproduce research
    dir: research
    cmds:
    - python main.py {{.CLI_ARGS}}

  dump:
    dir: dump/emulate
    desc: Dump using cooking simulator
    cmds:
    - cargo run --release --bin rdump --quiet -- {{.CLI_ARGS}}

  check:
    dir: dump/emulate
    desc: Check dumped data against sane values and compare dumps from console and emulate
    cmds:
    - cargo run --release --bin check --quiet -- {{.CLI_ARGS}}

  cook:
    dir: dump/emulate
    desc: Cook a recipe with emulator. Separate ingredients with commas
    cmds:
    - cargo run --bin cook-cli --quiet -- {{.CLI_ARGS}}

  cook-debug:
    dir: dump/emulate
    desc: Cook a recipe in debug mode
    cmds:
    - cargo run --bin cook-cli --features debug-print -- {{.CLI_ARGS}}

  read-test:
    dir: dump/emulate
    desc: Test database reading implementation
    cmds:
    - cargo run --release --bin test-read --quiet
