version: '3'

env:
  CONSOLE_ADDR: 192.168.0.161:5000 # can be overriden in .env
dotenv: [".env"]

tasks:
  research:
    desc: Reproduce research
    dir: research
    cmds:
    - python main.py {{.CLI_ARGS}}

  uconsole:
    aliases: [uc]
    dir: dump/console
    desc: Upload dumper mod to the console
    cmds:
    - lftp $CONSOLE_ADDR < scripts/lftp-upload.sh

  dump-console:
    dir: dump/console
    aliases: [dcon]
    desc: Download dumps from the console
    cmds:
    - mkdir -p raw
    - mkdir -p data
    - lftp $CONSOLE_ADDR < scripts/lftp-download.sh
    - python scripts/rename.py
    - rm -r raw

  dump-emulate:
    dir: dump/emulate
    aliases: [demu]
    desc: Dump using cooking.rs
    cmds:
    - cargo run --release --bin dump

  dcheck:
    dir: dump/check
    aliases: [c]
    desc: Check dumps
    cmds:
    - cargo run --release --bin check --quiet -- {{.CLI_ARGS}}

  inspect:
    dir: dump/check
    aliases: [i]
    desc: Inspect a dump error
    cmds:
    - cargo run --release --bin check --quiet -- --inspect {{.CLI_ARGS}}

  mismatch:
    dir: dump/check
    aliases: [m]
    desc: Inspect a chunk mismatch error
    cmds:
    - cargo run --release --bin check --quiet -- --mismatch {{.CLI_ARGS}}
    

  cook:
    dir: dump/emulate
    desc: Cook a recipe with emulator. Separate ingredients with commas
    cmds:
    - cargo run --bin cook --quiet -- {{.CLI_ARGS}}



#
# tasks:
#   build:
#     aliases: [b]
#     desc: Build the mod
#     cmds:
#       - megaton
#
#
#   download:
#     desc: Download logs and data from console
#     cmds:
#     - mkdir -p target/crash_reports/dumps
#     - lftp $CONSOLE_ADDR < scripts/lftp-download.sh
