[package]
name = "botw-recipe-dump-emulate"
version = "0.0.0"
edition = "2021"

[dependencies]
clap = { version = "=4.5.4", features = ["derive"] }
num_cpus = "1.16.0"

[dependencies.rcook]
package = "botw-recipe-cook"
path = "../../app/cook"

[dependencies.rdata]
package = "botw-recipe-data"
path = "../../app/data"

[[bin]]
name = "rdump"
path = "src/rdump.rs"
