[package]
name = "botw-recipe-dump-emulate"
version = "0.0.0"
edition = "2021"

[dependencies]

[dependencies.cooking]
path = "../../../cooking.rs"

[dependencies.botw-recipe-data]
path = "../../app/data"
