[package]
name = "botw-recipe"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bit-set = "0.5.3"
ctrlc = "3.2.4"
serde_json = "1.0.91"
serde_yaml = "0.9.16"
positioned-io = "0.3.1"
