version: '3'

tasks:
  install:
    desc: Install JS dependencies
    cmds:
    - npm install

  install-ci:
    cmds:
    - npm ci

  dev:
    desc: Run RDB in dev (watch) mode
    cmds:
    - npx tauri dev

  build-js:
    cmds:
    - npx tsc && npx vite build

  build:
    desc: Build RDB (release) binary
    cmds:
    - npx tauri build
